version: '2.1'

services:
  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: Seebak2021
      MYSQL_DATABASE: books_db
    ports:
      - "3306:3306"
    volumes:
      - data:/var/lib/mysql


volumes:
  data:
    name: mysql-db-data 